# Set up funding links for your project.
# Uncomment and fill in the options you use. See https://docs.github.com/sponsors
# This file is optional; remove if you do not want a Sponsor button.

# github: [OWNER]
# patreon: USERNAME
# open_collective: PROJECT_SLUG
# ko_fi: USERNAME
# buy_me_a_coffee: USERNAME
# custom: ["https://your-custom-donate-link.example.com"]
