blank_issues_enabled: false
contact_links:
  - name: Ask a question or get help (Discussions)
    url: ../../discussions
    about: Please use GitHub Discussions for Q&A, troubleshooting, and general help.
